/* Mock manuscript dataset for Ivy prototype.
   Shaped to match the real types in client/src/types/graph.ts */

const CHAPTERS = [
  { chapter_num: 1, chapter_title: "The Gull Inheritance", summary: ["Eline returns to Saltcombe after her grandmother's funeral.", "She finds an unopened letter dated 1962 addressed to a stranger.", "The lighthouse keeper, Tomas, recognizes the name."], key_events: ["Eline arrives in Saltcombe", "Discovery of the 1962 letter", "First conversation with Tomas"], characters: ["Eline Voss", "Tomas Brun", "Margit (deceased)"] },
  { chapter_num: 2, chapter_title: "Salt and Lacquer", summary: ["Eline opens the cottage and sorts her grandmother's belongings.", "She learns Margit kept the letter for sixty-three years.", "A neighbor warns her not to ask about the Hollens."], key_events: ["Cottage inventoried", "Margit's secret revealed", "Warning from the neighbor"], characters: ["Eline Voss", "Mrs. Halvarsen"] },
  { chapter_num: 3, chapter_title: "The Long Pier", summary: ["Tomas walks Eline to the lighthouse.", "He tells her about the night of the wreck in 1962.", "Eline sees a photograph of a young woman she does not recognize."], key_events: ["Walk to the lighthouse", "Story of the 1962 wreck", "Photograph of unknown woman"], characters: ["Eline Voss", "Tomas Brun"] },
  { chapter_num: 4, chapter_title: "Names on the Wall", summary: ["At the harbor master's office Eline finds the manifest.", "The unknown woman is listed as 'Aino H.' — presumed lost.", "Tomas insists Aino survived but never returned."], key_events: ["Manifest examined", "Aino H. identified", "Tomas's claim about Aino"], characters: ["Eline Voss", "Tomas Brun", "Aino Hollen"] },
  { chapter_num: 5, chapter_title: "What the Tide Keeps", summary: ["Eline finds Aino's diary hidden in the cottage chimney.", "The diary stops abruptly on the night of the wreck.", "She begins to suspect Margit was on the boat too."], key_events: ["Diary discovered", "Last diary entry read", "Margit's involvement suspected"], characters: ["Eline Voss", "Margit (in diary)", "Aino Hollen"] },
  { chapter_num: 6, chapter_title: "The Hollen House", summary: ["Eline visits the abandoned Hollen estate.", "She meets Per Hollen, Aino's nephew, who is hostile.", "Per claims his family was destroyed by 'the Voss woman'."], key_events: ["Visit to Hollen estate", "Confrontation with Per", "Accusation against Margit"], characters: ["Eline Voss", "Per Hollen"] },
  { chapter_num: 7, chapter_title: "Ledger of Small Mercies", summary: ["Eline cross-references Margit's bank ledger.", "Monthly payments to a P.O. box in Bergen since 1963.", "Tomas admits he forwarded the payments."], key_events: ["Ledger discovery", "Bergen P.O. box identified", "Tomas's admission"], characters: ["Eline Voss", "Tomas Brun"] },
  { chapter_num: 8, chapter_title: "A Door in Bergen", summary: ["Eline travels to Bergen and finds the P.O. box claimant.", "It is Aino Hollen, alive at 84.", "Aino refuses to speak and closes the door."], key_events: ["Journey to Bergen", "Aino found alive", "Door closed on Eline"], characters: ["Eline Voss", "Aino Hollen"] },
  { chapter_num: 9, chapter_title: "The Second Letter", summary: ["Aino sends Eline a letter with a single page from Margit's diary.", "The page describes a child given up the night of the wreck.", "Eline realizes the child was her father."], key_events: ["Letter from Aino arrives", "Diary page reveals a child", "Eline's parentage reframed"], characters: ["Eline Voss", "Aino Hollen", "Margit (in diary)"] },
  { chapter_num: 10, chapter_title: "Saltcombe, Again", summary: ["Eline returns to Saltcombe and burns the original 1962 letter.", "Tomas dies the following winter.", "Aino visits the cottage in spring; the two women sit in silence."], key_events: ["Letter burned", "Tomas's death", "Aino's visit to the cottage"], characters: ["Eline Voss", "Tomas Brun", "Aino Hollen"] },
];

const TIMELINE_EVENTS = [
  { event_id: "E001", description: "The Saltcombe wreck; Aino presumed lost at sea.", chapter_num: 3, chapter_title: "The Long Pier", order: 1, characters_present: ["Aino Hollen", "Margit", "Tomas Brun"], location: "Saltcombe harbor", causes: ["E002", "E003"], caused_by: [], time_reference: "October 1962", inferred_date: "1962-10", inferred_year: 1962, relative_time_anchor: null, confidence: 0.92 },
  { event_id: "E002", description: "Margit conceals Aino's survival and takes in the child.", chapter_num: 5, chapter_title: "What the Tide Keeps", order: 2, characters_present: ["Margit", "Aino Hollen"], location: "Saltcombe cottage", causes: ["E004"], caused_by: ["E001"], time_reference: "October 1962", inferred_date: "1962-10", inferred_year: 1962, relative_time_anchor: "the night of the wreck", confidence: 0.81 },
  { event_id: "E003", description: "Tomas begins forwarding monthly payments on Margit's behalf.", chapter_num: 7, chapter_title: "Ledger of Small Mercies", order: 3, characters_present: ["Margit", "Tomas Brun"], location: "Saltcombe", causes: [], caused_by: ["E001"], time_reference: "1963", inferred_date: "1963-01", inferred_year: 1963, relative_time_anchor: null, confidence: 0.88 },
  { event_id: "E004", description: "The child (Eline's father) is given to a family inland.", chapter_num: 9, chapter_title: "The Second Letter", order: 4, characters_present: ["Margit"], location: "Inland", causes: [], caused_by: ["E002"], time_reference: "Winter 1962", inferred_date: "1962-12", inferred_year: 1962, relative_time_anchor: null, confidence: 0.74 },
  { event_id: "E005", description: "Margit's death; estate passes to Eline.", chapter_num: 1, chapter_title: "The Gull Inheritance", order: 5, characters_present: ["Margit", "Eline Voss"], location: "Saltcombe", causes: ["E006"], caused_by: [], time_reference: "Spring (present)", inferred_date: null, inferred_year: null, relative_time_anchor: "shortly before Eline's return", confidence: 0.95 },
  { event_id: "E006", description: "Eline returns to Saltcombe.", chapter_num: 1, chapter_title: "The Gull Inheritance", order: 6, characters_present: ["Eline Voss"], location: "Saltcombe", causes: ["E007"], caused_by: ["E005"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: "after the funeral", confidence: 0.99 },
  { event_id: "E007", description: "Discovery of the 1962 letter in the cottage.", chapter_num: 1, chapter_title: "The Gull Inheritance", order: 7, characters_present: ["Eline Voss"], location: "Saltcombe cottage", causes: ["E008"], caused_by: ["E006"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.97 },
  { event_id: "E008", description: "Eline meets Tomas; the name on the letter is recognized.", chapter_num: 1, chapter_title: "The Gull Inheritance", order: 8, characters_present: ["Eline Voss", "Tomas Brun"], location: "Lighthouse path", causes: [], caused_by: ["E007"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.96 },
  { event_id: "E009", description: "Cottage inventory; warning from the neighbor.", chapter_num: 2, chapter_title: "Salt and Lacquer", order: 9, characters_present: ["Eline Voss", "Mrs. Halvarsen"], location: "Saltcombe cottage", causes: [], caused_by: [], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.9 },
  { event_id: "E010", description: "Tomas walks Eline to the lighthouse and tells the wreck story.", chapter_num: 3, chapter_title: "The Long Pier", order: 10, characters_present: ["Eline Voss", "Tomas Brun"], location: "Lighthouse", causes: ["E011"], caused_by: ["E008"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.93 },
  { event_id: "E011", description: "Eline finds Aino H. on the harbor manifest.", chapter_num: 4, chapter_title: "Names on the Wall", order: 11, characters_present: ["Eline Voss"], location: "Harbor master's office", causes: ["E013"], caused_by: ["E010"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.94 },
  { event_id: "E012", description: "Aino's diary is recovered from the chimney.", chapter_num: 5, chapter_title: "What the Tide Keeps", order: 12, characters_present: ["Eline Voss"], location: "Saltcombe cottage", causes: ["E013"], caused_by: ["E007"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.91 },
  { event_id: "E013", description: "Eline visits the Hollen estate; confronted by Per.", chapter_num: 6, chapter_title: "The Hollen House", order: 13, characters_present: ["Eline Voss", "Per Hollen"], location: "Hollen estate", causes: [], caused_by: ["E011", "E012"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.89 },
  { event_id: "E014", description: "The Bergen P.O. box is identified in Margit's ledger.", chapter_num: 7, chapter_title: "Ledger of Small Mercies", order: 14, characters_present: ["Eline Voss", "Tomas Brun"], location: "Saltcombe", causes: ["E015"], caused_by: ["E003"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.92 },
  { event_id: "E015", description: "Eline travels to Bergen and finds Aino alive at 84.", chapter_num: 8, chapter_title: "A Door in Bergen", order: 15, characters_present: ["Eline Voss", "Aino Hollen"], location: "Bergen", causes: ["E016"], caused_by: ["E014"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.97 },
  { event_id: "E016", description: "Aino sends a diary page revealing the child given up.", chapter_num: 9, chapter_title: "The Second Letter", order: 16, characters_present: ["Eline Voss", "Aino Hollen"], location: "Saltcombe (mail)", causes: ["E017"], caused_by: ["E015", "E004"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.86 },
  { event_id: "E017", description: "Eline burns the original 1962 letter.", chapter_num: 10, chapter_title: "Saltcombe, Again", order: 17, characters_present: ["Eline Voss"], location: "Saltcombe cottage", causes: [], caused_by: ["E016"], time_reference: null, inferred_date: null, inferred_year: null, relative_time_anchor: null, confidence: 0.95 },
  { event_id: "E018", description: "Tomas dies in the following winter.", chapter_num: 10, chapter_title: "Saltcombe, Again", order: 18, characters_present: ["Tomas Brun"], location: "Saltcombe", causes: [], caused_by: [], time_reference: "Winter (present + 1)", inferred_date: null, inferred_year: null, relative_time_anchor: "winter after Eline's return", confidence: 0.98 },
  { event_id: "E019", description: "Aino visits Eline at the cottage; the two sit in silence.", chapter_num: 10, chapter_title: "Saltcombe, Again", order: 19, characters_present: ["Eline Voss", "Aino Hollen"], location: "Saltcombe cottage", causes: [], caused_by: ["E018"], time_reference: "Spring (present + 1)", inferred_date: null, inferred_year: null, relative_time_anchor: "spring after Tomas's death", confidence: 0.93 },
];

const PLOT_HOLES = [
  { hole_id: "PH-01", hole_type: "Dead character reappearance", severity: "high", confidence: 0.94, description: "Aino Hollen is presumed lost in the 1962 wreck (Ch. 3) and listed as 'lost' on the harbor manifest (Ch. 4), yet appears alive in Bergen at age 84 (Ch. 8) without an in-text explanation of how the manifest was wrong.", chapters_involved: [3, 4, 8], characters_involved: ["Aino Hollen"], events_involved: ["E001", "E011", "E015"] },
  { hole_id: "PH-02", hole_type: "Timeline paradox", severity: "high", confidence: 0.88, description: "Margit's monthly payments to the Bergen P.O. box are described as starting in 1963 (Ch. 7), but Aino's diary stops on the night of the wreck in October 1962 with no indication she had relocated to Bergen yet.", chapters_involved: [5, 7], characters_involved: ["Margit", "Aino Hollen"], events_involved: ["E002", "E003"] },
  { hole_id: "PH-03", hole_type: "Location conflict", severity: "medium", confidence: 0.72, description: "In Ch. 6 Per Hollen claims his family was 'destroyed' by the Voss woman, but the Hollen estate is described as still occupied by Per — contradicting the framing of total destruction.", chapters_involved: [6], characters_involved: ["Per Hollen"], events_involved: ["E013"] },
  { hole_id: "PH-04", hole_type: "Unresolved setup", severity: "medium", confidence: 0.81, description: "Mrs. Halvarsen's warning in Ch. 2 ('don't ask about the Hollens') is never paid off — she does not reappear and her stake in the secret is never explained.", chapters_involved: [2], characters_involved: ["Mrs. Halvarsen"], events_involved: ["E009"] },
  { hole_id: "PH-05", hole_type: "Character knowledge gap", severity: "medium", confidence: 0.69, description: "Tomas admits in Ch. 7 to forwarding payments since 1963, but in Ch. 1 he reacts to the 1962 letter as if the name were merely familiar — not as the name of a person he has been actively protecting for sixty-three years.", chapters_involved: [1, 7], characters_involved: ["Tomas Brun"], events_involved: ["E008", "E003"] },
  { hole_id: "PH-06", hole_type: "Causal gap", severity: "low", confidence: 0.58, description: "The diary page Aino sends in Ch. 9 reveals a child was given up — but there is no explanation for why Aino chose this moment, after sixty-three years of silence, to surface that detail.", chapters_involved: [8, 9], characters_involved: ["Aino Hollen"], events_involved: ["E015", "E016"] },
  { hole_id: "PH-07", hole_type: "Temporal marker", severity: "low", confidence: 0.55, description: "Ch. 10 places Aino's visit in 'spring after Tomas's death' but the prior winter chapter does not specify which winter, making the year of the final scene ambiguous.", chapters_involved: [10], characters_involved: ["Aino Hollen", "Tomas Brun"], events_involved: ["E018", "E019"] },
];

const CHARACTERS = [
  { name: "Eline Voss", role: "protagonist", chapters: [1,2,3,4,5,6,7,8,9,10], event_count: 14 },
  { name: "Tomas Brun", role: "ally",        chapters: [1,3,4,7,10],          event_count: 8 },
  { name: "Aino Hollen", role: "revenant",   chapters: [4,5,8,9,10],          event_count: 7 },
  { name: "Margit",      role: "deceased",   chapters: [1,2,5,7,9],            event_count: 6 },
  { name: "Per Hollen",  role: "antagonist", chapters: [6],                    event_count: 1 },
  { name: "Mrs. Halvarsen", role: "minor",   chapters: [2],                    event_count: 1 },
];

const RECENT_MANUSCRIPTS = [
  { id: "ms-001", title: "The Saltcombe Letter", author: "K. Vinter",      pages: 312, chapters: 10, status: "complete",          updated: "2 hours ago",  issues: 7,  events: 19 },
  { id: "ms-002", title: "Brass and Bone",        author: "M. Okafor",      pages: 418, chapters: 14, status: "timeline_in_progress", updated: "yesterday",   issues: 0,  events: 0  },
  { id: "ms-003", title: "Northwater",            author: "J. Lindqvist",   pages: 286, chapters: 9,  status: "complete",          updated: "3 days ago",   issues: 12, events: 24 },
  { id: "ms-004", title: "The Cartographer's Wife", author: "R. Halloran",  pages: 504, chapters: 22, status: "complete",          updated: "last week",    issues: 4,  events: 41 },
  { id: "ms-005", title: "An Honest Country",      author: "A. Petros",     pages: 198, chapters: 8,  status: "ingestion_in_progress", updated: "moments ago", issues: 0, events: 0 },
];

window.IVY_DATA = { CHAPTERS, TIMELINE_EVENTS, PLOT_HOLES, CHARACTERS, RECENT_MANUSCRIPTS };
